[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "api"

[build.environment]
  NODE_VERSION = "20"
  EDGE_HANDLER = "true"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "dist/assets/*"
  SECRETS_SCAN_OMIT_KEYS = "VITE_OPENAI_API_KEY"

[[edge_functions]]
  path = "/webhook"
  function = "webhook"

[[edge_functions]]
  path = "/create-customer"
  function = "create-customer"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/edge-functions/webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/create-customer"
  to = "/.netlify/edge-functions/create-customer"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/webhook"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, stripe-signature"

[[headers]]
  for = "/create-customer"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"