[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/api/create-meal-plan"
  function = "create-meal-plan"

[[edge_functions]]
  path = "/api/get-meal-plan"
  function = "get-meal-plan"

[[edge_functions]]
  path = "/api/webhook"
  function = "webhook"

[[edge_functions]]
  path = "/api/create-customer"
  function = "create-customer"

[[edge_functions]]
  path = "/api/create-checkout-session"
  function = "create-checkout-session"

[[edge_functions]]
  path = "/api/create-portal-session"
  function = "create-portal-session"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, stripe-signature"