[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "api"

[build.environment]
  NODE_VERSION = "20"
  EDGE_HANDLER = "true"

[[edge_functions]]
  path = "/webhook"
  function = "webhook"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/edge-functions/webhook"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/webhook"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, stripe-signature"